[build]
  publish = "frontend/build"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  port = 3000
  functions = "netlify/functions"

[context.production.environment]
  NODE_ENV = "production"
